### GET main
GET http://localhost:3000

### GET all Items
GET http://localhost:3000/inventory

### POST / Create Item
POST http://localhost:3000/inventory HTTP/1.1
Content-Type: application/json

{
    "sku": "any-001",
    "name": "any",
    "description": "any",
    "unit": "kg",
    "unit_weight": 1,
    "unit_cost": 1,
    "stock": 1
}

### GET single item
GET http://localhost:3000/inventory/65153a79d0deaddc07621db8

### PUT / Update Item
PUT http://localhost:3000/inventory/65153a79d0deaddc07621db8 HTTP/1.1
Content-Type: application/json

{
    "sku": "put-001",
    "name": "put",
    "description": "put",
    "unit": "kg",
    "unit_weight": 1,
    "unit_cost": 1,
    "stock": 1
}

### Delete Item
DELETE http://localhost:3000/inventory/65153a79d0deaddc07621db8


### Get all suppliers
GET http://localhost:3000/supplier

### Create one supplier
POST http://localhost:3000/supplier HTTP/1.1
Content-Type: application/json

{
    "supplier": "post",
    "address": "post",
    "phone": "123-4567",
    "url": "https://www.google.com/"
}

### Get one supplier by id
GET http://localhost:3000/supplier/651537497df0e851d5de26a0

### update one supplier
PUT http://localhost:3000/supplier/651537497df0e851d5de26a0 HTTP/1.1
Content-Type: application/json

{
    "supplier": "put",
    "address": "put",
    "phone": "123-4567",
    "url": "https://www.google.com/"
}

### Delete one supplier
DELETE http://localhost:3000/supplier/651537497df0e851d5de26a0